# Generated by Django 4.0.4 on 2022-05-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='zone',
        ),
    ]
