# Generated by Django 4.0.4 on 2022-04-26 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point_workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_short_name', models.CharField(max_length=20, unique=True)),
                ('role_full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='point_workshop.zone'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserAssignedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='point_workshop.branch')),
                ('role', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='point_workshop.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='point_workshop.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
