# Generated by Django 4.0.4 on 2022-05-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_workshop', '0002_remove_state_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneStateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='point_workshop.state')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='point_workshop.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
