# Generated by Django 4.0.4 on 2022-05-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_workshop', '0003_zonestatemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonestatemap',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_workshop.zone'),
        ),
    ]
