# Generated by Django 4.0.4 on 2022-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_short_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
