# Generated by Django 4.0.4 on 2022-04-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
